[server]
port=8080

[mysql]
enable = false
orm = false
# <user>[:password]@tcp(address)/<Database>[?parseTime=true][&loc=Local]
# address: host[:port] | /path/to/unix/socket/file
dsn="<user>[:password]@tcp(localhost)/<Database>[?parseTime=true][&loc=Local]"
maxIdleConns=0
maxOpenConns=50

[mongodb]
enable = false
url="mongodb://localhost:27017"

[redis]
enable = true
address = "localhost:6379"
password = ""
DB = 0
poolSize = 5

[business]
ttl = 1200
md5PreLen = 4

[jwt]
headerName = "token"
# key to sign jwt
key="<secret key>"
# token 过期时间，单位小时；为零时表示不过期
exp = 24

[tls]
enable = false
certFile = "cert.pem"
keyFile = "cert.key"

[log]
# available values :"debug" "info" "error" "fatal" "panic"
level = "debug"
# logfile = "share.log"
logfile = ""
showFullTime = true
reportCaller = false

[cors]
# "*" means allow all origins
allowOrigins = [ "*" ]
allowMethods = [ "GET", "POST" ]
allowHeaders = [ "Origin", "Content-Length", "Content-Type" ]
# unit: second
maxAge = 43200
